### ISSUE TITLE
Validation fails if a / resource exists

### ISSUE THREAD

**Issue by ddossot** [nidi3/raml-tester-proxy#11]
I've added the following resource:

``` yaml
/:
  securedBy: []
  get:
    description: |
      Global API meta-information.
    responses:
      200:
        body:
          application/json:
            schema: api_root
```

and suddenly all the other resources are now reported wrong, with errors like:

<pre>
2015-03-25 11:41:10,332 ERROR - <1> GET http://localhost:9090/accounts from 127.0.0.1
           Request:  [Resource '/accounts' is not defined]
           Response: []
</pre>

**Comment by nidi3** [comment]
this is an issue for raml-tester https://github.com/nidi3/raml-tester/issues/20

**Comment by nidi3** [comment]
Btw. are you using security?

**Comment by ddossot** [comment]
Not on this particular resource, but on everything other resources yes.

**Comment by nidi3** [comment]
Cause I didn't use it till now and it's not implemented in raml-tester. But as long as it doesn't hinder you, it's ok.

**Comment by ddossot** [comment]
I'm using basic auth for my integration tests via raml-tester-proxy and everything works great :+1:

**Comment by nidi3** [comment]
The Authentication header is a known one and therefore accepted without defining it. Works as designed. :)

**Comment by ddossot** [comment]
Any ETA for a release? Now that the issue has been fixed in raml-tester, it would be great to have it in the proxy :wink:

**Comment by nidi3** [comment]
I want to do some tests with async mode, then I'll do a release.
Should be this week.

**Comment by ddossot** [comment]
FYI everything works beautifully with `0.0.4` Thank you :bow:

**Comment by nidi3** [comment]
nice to hear :smile:
