### ISSUE TITLE
NPE when starting asynchronously

### ISSUE THREAD

**Issue by ddossot** [nidi3/raml-tester-proxy#18]
When starting the proxy standalone `0.0.4` with these options:

```
-p9090 -thttp://localhost:8080
-rhttp://localhost:8080/raml/v0.4/api.raml -s./target -fJSON
-i -a
```

I get this in the command line:

```
08:58:02.498 INFO  - g.n.ramlproxy.report.Reporter : Reporting in JSON format into: ./target
null
Exception in thread "main" java.lang.NullPointerException
    at guru.nidi.ramlproxy.RamlProxy.startNewServer(RamlProxy.java:110)
    at guru.nidi.ramlproxy.RamlProxy.startServerAsync(RamlProxy.java:49)
    at guru.nidi.ramlproxy.cli.Main.main(Main.java:40)
```

After that, the proxy is running, it works fine but can't be controlled:

```
$ java -jar raml-tester-standalone-0.0.4.jar ping
Could not connect to proxy, start a new one.
```

If I kill its process, it correctly outputs the usage file and stops.

**Comment by nidi3** [comment]
That's probably a timeout problem. 
If you can build the project, can you try setting a higher value at SubProcess:70 ?

You have to specify the port when pinging the server, then it should work.

**Comment by ddossot** [comment]
OK so when I specify the port, the async running proxy responds and is controllable.

So the current issue is not a blocker, it's just a little dirty on start.

I'll try with a higher timeout and let you know.

**Comment by ddossot** [comment]
I can confirm that with `return readLine(10);` the proxy starts flawlessly. I guess the default timeout of 1 second is too short for the non trivial RAML file I'm loading...
