### ISSUE TITLE
Can't test a remote API over HTTPS

### ISSUE THREAD

**Issue by ddossot** [nidi3/raml-tester-proxy#2]
It seems that the proxy doesn't contact the remote API over HTTPS at all.

I'm starting it with:

```
java -jar target/raml-tester-proxy-0.0.2-SNAPSHOT.jar -p 8090 -t https://<my_host> -r https://<my_host>/raml/v1/api.raml -b https://<my_host> -s .
```

I see it loads the RAML definition correctly and the related JSON schemas as well.

When I send a request, I see in the proxy logs:

```
2015-01-16 15:51:00,756 ERROR - <1> POST http://localhost:8090/<path> from 127.0.0.1
       Request:  []
       Response: [Response(200) is not defined on action(POST /<path>)]
```

but the remote server has not been contacted at all. If it had been contacted, it would have returned the expected `204`.

Note that `curl` is blocked waiting for the proxy response to be closed:

```
< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
* Server Jetty(9.1.z-SNAPSHOT) is not blacklisted
< Server: Jetty(9.1.z-SNAPSHOT)
< 
```

which never happens.

If I switch from HTTP to HTTPS, everything works fine.

**Comment by nidi3** [comment]
hm, I have not really an idea... let me take a look at this over the weekend.

**Comment by nidi3** [comment]
Should be fixed now, but not 100% sure. Can you test it?

**Comment by ddossot** [comment]
I'm super happy to confirm it works great! Thank you :+1:
