### ISSUE TITLE
No output from proxy

### ISSUE THREAD

**Issue by mik01aj** [nidi3/raml-tester-proxy#24]
This looks related to https://github.com/nidi3/raml-tester-proxy/issues/22.

The problem is, as I saw in the above issue that `file://` urls are problematic, I used `python -m SimpleHTTPServer` to start a local server. Then I started the proxy with this server, and it loaded the RAML definitions (I saw that it reqeuested the `include`d files), but it's still neither answering any requests  nor producing any log output. It just created an empty directory for the logs, nothing more.

Here's the full command line and output (note that these lines starting with `127.0.0.1` come from the Python server, not the `raml-proxy`): 

```
$ raml-tester -rhttp://localhost:8000/topics/topics.raml -thttp://localhost:7770 -saaa -ftext
17:25:56.391 INFO  - g.n.ramlproxy.report.Reporter : Reporting in TEXT format into: aaa
127.0.0.1 - - [27/Jul/2015 17:25:56] "GET /topics/topics.raml HTTP/1.1" 200 -
127.0.0.1 - - [27/Jul/2015 17:25:57] "GET /topics/../include/resourceTypes/collection.yaml HTTP/1.1" 200 -
127.0.0.1 - - [27/Jul/2015 17:25:57] "GET /topics/../include/resourceTypes/collection-item.yaml HTTP/1.1" 200 -
127.0.0.1 - - [27/Jul/2015 17:25:57] "GET /topics/../include/resourceTypes/readonly-collection.yaml HTTP/1.1" 200 -
127.0.0.1 - - [27/Jul/2015 17:25:57] "GET /topics/../include/resourceTypes/readonly-collection-item.yaml HTTP/1.1" 200 -
127.0.0.1 - - [27/Jul/2015 17:25:57] "GET /topics/../include/resourceTypes/writeonly-collection.yaml HTTP/1.1" 200 -
127.0.0.1 - - [27/Jul/2015 17:25:57] "GET /topics/../include/resourceTypes/writeonly-collection-item.yaml HTTP/1.1" 200 -
127.0.0.1 - - [27/Jul/2015 17:25:57] "GET /topics/../include/traits/orderable.yaml HTTP/1.1" 200 -
127.0.0.1 - - [27/Jul/2015 17:25:57] "GET /topics/../include/traits/pageable.yaml HTTP/1.1" 200 -
17:25:57.951 INFO  - g.nidi.ramlproxy.ProxyServlet : Proxy started


^C
```

I'm using version `0.0.4` from npm (https://github.com/nidi3/raml-tester-js).

**Comment by nidi3** [comment]
I think the problem in #22 is a missing baseUri definition in the RAML. Could this also be your case?

Anyways, 0.0.4 is a very old release. 
I'm going to release a new one based on raml-tester 0.8.2 which fixes the baseUri problem and logs any occurring problems.

**Comment by nidi3** [comment]
Ok, there's a new version 0.8.3, can you try with it?

**Comment by mik01aj** [comment]
Looks like fixed. I get responses from the proxy and I see the logs in the console. Thanks.
